fake_input_data:
  path: '.\data\fakepricedata\'

fake_output_data:
  path: '.\data\pricecategorizeddata\'

histogram_optional_keys:
  zscore: 'ZSCORE'

output_plots:
  path: '.\data\histograms\'

price_category:
  number: 4
