fake_input_data:
  #Windows path: '.\data\fakepricedata\'
  path: './data/fakepricedata/'
fake_output_data:
  #Windows path: '.\data\pricecategorizeddata\'
  path: './data/pricecategorizeddata/'
histogram_optional_keys:
  zscore: 'ZSCORE'

output_plots:
  #Windows path: '.\data\histograms\'
  path: './data/histograms/'
price_category:
  number: 4
